# Homework #5

How to do it? Uploading your .ipynb file into the corresponding homework in the LMS system. Any delay will not be accepted. 

##  Question 1: (5 points)

### Multiply a matrix by another matrix, we need to do the dot product of rows and columns.  Let a user input two matrices A and B, calculate the matrix multiplication AB if possible.   

How to multiply two matrices? 
* Reference: https://en.wikipedia.org/wiki/Matrix_multiplication

In [1]:
import numpy as np 

def getMatrixFromUser():
    R = int(input("Enter the number of rows: ")) 
    C = int(input("Enter the number of columns: ")) 

    entries = input("Enter the entries in a single line (separated by space): ") 

    entries = list(map(int, entries.split())) 

    matrix = np.array(entries).reshape(R, C) 
    print(matrix) 
    return matrix

print("Input matrix A:")
A = getMatrixFromUser()

print("Input matrix B:")
B = getMatrixFromUser()

Input matrix A:
Enter the number of rows: 2
Enter the number of columns: 2
Enter the entries in a single line (separated by space): 1 2 3 4
[[1 2]
 [3 4]]
Input matrix B:
Enter the number of rows: 2
Enter the number of columns: 2
Enter the entries in a single line (separated by space): 1 2 3 4
[[1 2]
 [3 4]]


In [2]:
C = np.matmul(A, B)
print(C)

[[ 7 10]
 [15 22]]


##  Question 2: (5 points)

### Calculate the determinant of a given square matrix S

One way of computing the determinant of an n×n matrix A is to use the  cofactor expansion
* Referecne: https://people.richland.edu/james/lecture/m116/matrices/determinant.html

In [3]:
D = getMatrixFromUser()
det = np.linalg.det(D)
print(det) # may have a little rounding error due to compilation by LU factorization with LAPACK routine z/dgetrf

Enter the number of rows: 2
Enter the number of columns: 2
Enter the entries in a single line (separated by space): 1 2 3 4
[[1 2]
 [3 4]]
-2.0000000000000004
